### ISSUE TITLE
Created github Kanban board

### ISSUE THREAD

**Issue by tonnytech** [yusufobr/catalog-of-things#29]
Dear Reviewer,

All the group members discussed and distributed the tasks according to the instructions

Project link: https://github.com/yusufobr/catalog-of-things

We are a team of 3 members
@yusufobr : Team member #1 
@tonnytech : Team member #2 
@clin2on3mun : Team member #3

**Comment by anagudelogu** [comment]
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @tonnytech @yusufobr @clin2on3mun, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub's project features 🥇 

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please make sure that all your cards has the requested structure: `[Xpts] - Title`. Currently there are some missing the points:

![image](https://github.com/yusufobr/catalog-of-things/assets/77069011/96451575-b4f7-4175-a7c3-cc0bbebe5b41)


- [ ] Please consider distributing the workload evenly. Currently, here's the distribution (in points):

@yusufobr : 10 pts
@tonnytech : 17.5 pts
@clin2on3mun: 8 pts

Make sure that the difference is no greater than 5 pts.

- [ ] There are some tasks missing for Team member 3:

![image](https://github.com/yusufobr/catalog-of-things/assets/77069011/4c3989cf-ba7c-441d-8514-1be55b71432f)

![image](https://github.com/yusufobr/catalog-of-things/assets/77069011/4edaa7f3-a6cc-4067-9f92-a35cf3bdd9c5)

Please consider adding them! 🤓 🔧 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by codepantha** [comment]
# STATUS: APPROVED 🟢 🚀 

## Hi team 👋, 

Great job implementing the required changes 👏 
Your project is complete!  There is nothing else to say other than... it's time to start building you project :shipit: 🚀 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/2RGhmKXcl0ViM/giphy.gif"/>

## Highlights 🎯 
✔️ Set up kanban board 📌 
✔️ Tasks shared fairly amongst team  members 📌

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] The project link which you have provided in your PR description should lead to the the [kanban board here](https://github.com/yusufobr/catalog-of-things/projects/1). Please consider making this change 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
